### ISSUE TITLE
Drupal settings don't seem to be converted to CMI correctly

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/override_node_options#11]
I'm testing a new D7 upgrade that includes this module and I'm seeing this warning:

> Warning: in_array() expects parameter 2 to be array, null given in override_node_options_permission() (line 20 of /app/modules/contrib/override_node_options/override_node_options.module).

> Warning: in_array() expects parameter 2 to be array, null given in override_node_options_permission() (line 53 of /app/modules/contrib/override_node_options/override_node_options.module).

**Comment by laryn** [comment]
Saving the configuration form fixes it. It looks like this may be due to the Drupal 7 upgrade path not functioning correctly (settings were not carried over to the Backdrop site).

**Comment by jenlampton** [comment]
It doesn't appear that there was any update at all.  I've added one, and also a `hook_config_info()` implementation.
