### ISSUE TITLE
Manual installation fails due to missing 'type' attribute in test info file

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/override_node_options#5]
I've tried to install *Override Node options* manually (because it's [not listed in the Project Browser](https://github.com/backdrop-contrib/override_node_options/issues/6)) using the URL `https://github.com/backdrop-contrib/override_node_options/archive/1.x-1.13.0.zip` and also uploading the Github `.zip` file. The manual installation didn't work, and I saw this message:

> The info file (temporary://update-extraction-b3b7f6c3/override_node_options-1.x-1.13.0/tests/override_node_options.tests.info) does not define a 'type' attribute.

**Comment by jenlampton** [comment]
The latest release contains the type attribute. https://github.com/backdrop-contrib/override_node_options/releases/tag/1.x-1.13.0
