### ISSUE TITLE
Module not available in Project browser and on b.org

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/override_node_options#6]
While there is a working [release](https://github.com/backdrop-contrib/override_node_options/releases/tag/1.x-1.13.0), *Override Node Options* isn't available in the Backdrop Project browser, and I can't even find it on https://backdropcms.org/modules.

@docwilmot suggested in Gitter: "looks like the packager didnt fire (...) just needs a re-release". Can you try that, @jenlampton ? Would be great! The module is quite helpful and deserves some visibility in my opinion.

**Comment by jenlampton** [comment]
The latest release contains the type attribute. 
https://github.com/backdrop-contrib/override_node_options/releases/tag/1.x-1.13.0

**Comment by olafgrabienski** [comment]
Thanks @jenlampton, and confirmed: The module is now available in the Backdrop Project browser and on [backdropcms.org](https://backdropcms.org/project/override_node_options).
