### ISSUE TITLE
Override Node Options doesn't play well with Backdrop's new scheduled publishing feature

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/override_node_options#7]
The publishing options of Backdrop core have been extended by the "Publish for later" option. A person with the `Override MY-CONTENT-TYPE published option` permission is able to select the option, but she or he is not able to choose a date and time for schedule publishing.

Related core issue: https://github.com/backdrop/backdrop-issues/issues/3731

edit: The core issue ~~has a working PR which~~ is fixed but has a conflict with *Override Node Options*, see next comment.

**Comment by olafgrabienski** [comment]
Interestingly, the current PR for the [core issue mentioned above](https://github.com/backdrop/backdrop-issues/issues/3731), changes the situation quite a bit: When *Override Node Options* is enabled,

- a user without the `Administer content` permission (and also without `Override MY-CONTENT-TYPE published option`) is able to change an existing scheduled date, and
- the same user is able to choose a scheduled date for a node which had formerly been saved as draft.

Both things shouldn't be possible. I noticed they happen even if the user in question has no *Override Node Options* related permissions at all. But when I disable *Override Node Options*, the PR which fixes the issue with scheduled content, works fine.

Conclusion: It seems that *Override Node Options* needs some adaptions regarding the (relatively new) scheduling feature in core.

**Comment by herbdool** [comment]
I took a look at this. I believe we'll need the core PR in order for this module to be able to override the scheduling field. And then this module can add access control to the scheduling field directly. So might need to wait for the core change first.

**Comment by herbdool** [comment]
@olafgrabienski I think it only requires this https://github.com/herbdool/override_node_options/pull/1. However, this will rely on the core PR being accepted.

**Comment by olafgrabienski** [comment]
@herbdool I've tested https://github.com/herbdool/override_node_options/pull/1 on a local test site, looks good!

With the PR,

- user A with the `Override MY-CONTENT-TYPE published option` permission is still able to select the option (as expected) and he/she is now also able to choose a date and time for schedule publishing (this part didn't work before),
- user B without `Administer content` and also without `Override MY-CONTENT-TYPE published option` isn't anymore able to change an existing scheduled date,
- the same user B isn't anymore able to choose a scheduled date for a node which had formerly been saved as draft.

Everything as expected now, I guess!

**Comment by herbdool** [comment]
So I guess it's RTBC. Thanks @olafgrabienski. cc @jenlampton

**Comment by olafgrabienski** [comment]
Coming back to this: The related core issue https://github.com/backdrop/backdrop-issues/issues/3731 has been fixed for a while, and there is a [working PR](https://github.com/herbdool/override_node_options/pull/1) by @herbdool for this *Override Node Options* issue. @jenlampton Can you have a look at Herb's PR?

**Comment by olafgrabienski** [comment]
@jenlampton Friendly reminder: can you have a look at @herbdool's PR which fixes an "Override Node Option" issue with the Backdrop core content scheduling feature?

- PR: https://github.com/herbdool/override_node_options/pull/1
- What the PR does: https://github.com/backdrop-contrib/override_node_options/issues/7#issuecomment-494802533

**Comment by herbdool** [comment]
I've created PR properly now against this project: https://github.com/backdrop-contrib/override_node_options/pull/8 @laryn.

**Comment by olafgrabienski** [comment]
@jenlampton Thanks for merging @herbdool 's PR. I've tested the module including that commit, and it works well for me regarding published and scheduled access control. Are you planning to make a new release?

**Comment by jenlampton** [comment]
> Are you planning to make a new release? 

Sure. 

edit: https://github.com/backdrop-contrib/override_node_options/releases/tag/1.x-1.13.1

**Comment by olafgrabienski** [comment]
Great, many thanks!
